### PR TITLE
Max heap to connect to best suited peers.

### PR DESCRIPTION
**Pull request by yuansong862**

### CODE REVIEW

**Comment by ibudisteanu** [comment]
It will take me some time to review your changes...

**Comment by ibudisteanu** [comment]
Your proposal is to use the score to get the best peer to connect? Right? I guess your solution won't work if the full node might want to connect in parallel to different nodes, not just one by one.

**Comment by yuansong862** [comment]
Yes you are right.
You can use sorted set to replace the max heap. This way the first u known_nodes that be retrieved and selected.

**Comment by ibudisteanu** [comment]
I like it.

**Comment by ibudisteanu** [comment]
I accepted your pull request! Very good work

**Comment by ibudisteanu** [comment]
Check this commit https://github.com/PandoraPay/go-pandora-pay/commit/27f5cf447718e60d7d87220ad3ad1e5f3e8e3dc3

**Comment by ibudisteanu** [comment]
When I was testing your code I discovered a serious bug in the Heap implementation https://github.com/PandoraPay/go-pandora-pay/commit/df04b95bd107086459cc90cc82eb9268505b68f1

**Pull request merged**
