### PR TITLE
Pull request with suggestions for improvement.

### PR DESCRIPTION
**Pull request by taariq-saad**
I am uploading this pull request with suggestions for improvement. The code implements a special transaction script to enable conditional anonymous payments. Payload recipient will receive its payment in pending status. When the multisig threshold is reached, the recipient receives their payment. When the time limit expires, the amount will be returned to the sender. Instead of multisig threshold, there could be a hash proving the knowledge of a secret. This simple scheme will allow atomic swaps between other chains and Pandora Pay. 

A few serious bugs were discovered and fixed. Warmest regards!

### CODE REVIEW

**Comment by ibudisteanu** [comment]
Woow! This is such a big pull request! It will take me some time to review your changes.

**Comment by ibudisteanu** [comment]
Basically you created a new tx script to allow conditional zether payment. To proceed with the payload or to refund it?

**Comment by taariq-saad** [comment]
yes.

**Comment by ibudisteanu** [comment]
It is a really interesting proposal. It intrigues me how it works.

**Comment by taariq-saad** [comment]
There are two cases:
- Add encrypted ciphertexts to recipients
- Add negated encrypted ciphertext to senders 

It is very important that the sender's fee is zero and no burning values, otherwise there will be double spending.

**Comment by ibudisteanu** [comment]
Ok. Thank you for your explanation. Now it makes sense.

**Comment by ibudisteanu** [comment]
I was trying to run a test net with your changes. I noticed quite a few crashes. Did you run a test net ?

**Comment by taariq-saad** [comment]
Our team has reviewed the changes by running a local network. After further investigations we have identified and resolved some of the issues you may have found in our proposal.

**Comment by ibudisteanu** [comment]
I think some files are missing... I merged your Pull request but some files looks like missing from the project ?

**Comment by taariq-saad** [comment]
What do you mean some files are missing?

**Comment by ibudisteanu** [comment]
There are some files missing. When I tried to run a test net with all your changes some of the files are missing from the repository including "pandora-pay/helpers/files", "pandora-pay/blockchain/data_storage/pending_future_list/pending_future" and many others.  I think you forgot to commit all the files...

**Comment by taariq-saad** [comment]
ok I see now. I will commit the missing files shortly.

**Comment by taariq-saad** [comment]
Commit https://github.com/PandoraPay/go-pandora-pay/pull/44

**Pull request merged**
