### PR TITLE
Add GitHub workflow

### PR DESCRIPTION
**Pull request by fl0ge**
Add GitHub workflow to build go and wasm
Fix go link in documentation

### CODE REVIEW

**Comment by ibudisteanu** [comment]
@fl0ge any idea of how to use it ? I have never used Github workflow before. Awesome work btw

**Comment by fl0ge** [comment]
@ibudisteanu I've created a basic workflow that will build with go build and build the webassembly package, on Ubuntu with go 1.18. As a CICD pipeline, it can be used to execute tests (there aren't any for now), deploy some packages (e.g. wasm) to a repository or package manager, or it can also be possible to do some deployment, depending on the hosting provider and possibilities.
Thus, the ultimate possibility may be to automatically deploy to a production environment or to testnet, after testing builds and maybe with some additional tests, if relevant.

**Comment by ibudisteanu** [comment]
Awesome. There are many tests written. Some of them were not not maintained.

**Comment by ibudisteanu** [comment]
Golang has a built-in unit testing system that is extremely simple and fast.

**Comment by fl0ge** [comment]
Ok my bad.
I was executing
go test -v .
and the result was
?   	pandora-pay	[no test files]
I will have a look to check if the tests can be executed in the workflow

**Comment by ibudisteanu** [comment]
Maybe I didn't configure the unit testing right. I have tested them manually, one by one. Here is one example https://github.com/PandoraPay/go-pandora-pay/blob/main/addresses/address_test.go

**Comment by fl0ge** [comment]
I found a workaround to execute tests in the two directories that have files with _test.go suffix: addresses and helpers
I've submitted a new PR for that: #21

**Pull request merged**
